<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-P2PCEEJ" ignored="3" name="Successful Login with Valid Credentials" tests="4" failures="1" timestamp="15 May 2020 00:20:55 GMT" time="0.099" errors="0">
  <testcase name="createCustomer" time="0.016" classname="demo.basic.TestNGDemo"/>
  <testcase name="deleteCustomer" time="0.005" classname="demo.basic.TestNGDemo"/>
  <testcase name="editCustomer" time="0.002" classname="demo.basic.TestNGDemo"/>
  <testcase name="addPhoto" time="0.006" classname="demo.basic.TestNGDemotwo">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at demo.basic.TestNGDemotwo.addPhoto(TestNGDemotwo.java:11)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- addPhoto -->
  <testcase name="loginTest" time="0.0" classname="demo.basic.TestNGDemo">
    <ignored/>
  </testcase> <!-- loginTest -->
  <testcase name="loginTestGetTitle" time="0.0" classname="demo.basic.TestNGDemo">
    <ignored/>
  </testcase> <!-- loginTestGetTitle -->
  <testcase name="logOutTest" time="0.0" classname="demo.basic.TestNGDemo">
    <ignored/>
  </testcase> <!-- logOutTest -->
</testsuite> <!-- Successful Login with Valid Credentials -->
